### ISSUE TITLE
"WARNING: Exception: [Errno 32] Broken pipe" when SCSS rules are too long

### ISSUE THREAD

**Issue by webartov** [attenzione/SublimeLinter-scss-lint#55]
Noticed that SublimeLinter-scss-lint stopped working, in console I saw the following error:
`WARNING: Exception: [Errno 32] Broken pipe`
After spending like 3hrs trying to find a fix I found out that the issue happens only at the specific condition.
It seems that SublimeLinter-scss-lint fails when there are many rules like below
**How to reproduce:** just copy-paste the code below until you get to line 130
```scss
@include m(medium) {
  font-size: $--button-medium-font-size;
  padding: $--button-medium-padding-vertical $--button-medium-padding-horizontal;
}
```
After that you'll see the following error:
https://monosnap.com/file/4Wh0H3uUogTrf0USJ84p4GO9lcJkV5
https://monosnap.com/file/3ZeL7HOewnH97emDnw2V6FccveYrSr
